import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/features/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      "colors": {
        "on-secondary-fixed-variant": "#474646",
        "surface-bright": "#f9f9f7",
        "surface-container-highest": "#e2e3e1",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed-variant": "#6b3b00",
        "surface-variant": "#e2e3e1",
        "secondary-fixed": "#e5e2e1",
        "surface-dim": "#dadad8",
        "surface-container": "#eeeeec",
        "inverse-surface": "#2f3130",
        "outline": "#877363",
        "gallery-white": "#FFFFFF",
        "primary-fixed-dim": "#ffb875",
        "surface-container-high": "#e8e8e6",
        "error": "#ba1a1a",
        "inverse-on-surface": "#f1f1ef",
        "on-primary": "#ffffff",
        "tashtep-orange": "#F39223",
        "surface-tint": "#8d4f00",
        "background": "#f9f9f7",
        "primary-container": "#f39223",
        "on-primary-container": "#5e3300",
        "on-primary-fixed": "#2d1600",
        "on-tertiary-container": "#3d3e42",
        "surface": "#f9f9f7",
        "secondary-fixed-dim": "#c8c6c5",
        "error-container": "#ffdad6",
        "on-surface-variant": "#544435",
        "primary-fixed": "#ffdcc0",
        "primary": "#8d4f00",
        "on-secondary-fixed": "#1c1b1b",
        "on-error": "#ffffff",
        "secondary": "#5f5e5e",
        "tertiary-container": "#a9a9ae",
        "tertiary-fixed": "#e3e2e7",
        "tertiary-fixed-dim": "#c7c6cb",
        "tertiary": "#5d5e63",
        "on-surface": "#1a1c1b",
        "surface-container-low": "#f4f4f2",
        "stone": "#F8F8F9",
        "on-tertiary-fixed-variant": "#46464b",
        "secondary-container": "#e5e2e1",
        "on-secondary": "#ffffff",
        "obsidian": "#111111",
        "outline-variant": "#dac2af",
        "charcoal": "#333333",
        "on-tertiary-fixed": "#1a1b1f",
        "on-error-container": "#93000a",
        "on-tertiary": "#ffffff",
        "on-secondary-container": "#656464",
        "inverse-primary": "#ffb875",
        "on-background": "#1a1c1b",
        "soft-border": "#EAE7E1"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
        "2xl": "1rem"
      },
      "spacing": {
        "micro-md": "16px",
        "macro-sm": "32px",
        "gutter": "24px",
        "container-max": "1440px",
        "macro-md": "64px",
        "macro-lg": "128px",
        "micro-xs": "4px",
        "micro-sm": "8px"
      },
      "maxWidth": {
        "container-max": "1440px"
      },
      "fontFamily": {
        "headline-md": ["Cairo", "sans-serif"],
        "display-hero-mobile": ["Cairo", "sans-serif"],
        "body-lg": ["Tajawal", "sans-serif"],
        "technical-mono": ["IBM Plex Sans Arabic", "sans-serif"],
        "display-hero": ["Cairo", "sans-serif"],
        "body-md": ["Tajawal", "sans-serif"],
        "label-md": ["Tajawal", "sans-serif"],
        "headline-lg-mobile": ["Cairo", "sans-serif"],
        "headline-lg": ["Cairo", "sans-serif"],
        "sans": ["var(--font-tajawal)", "sans-serif"],
      },
      "fontSize": {
        "headline-md": ["32px", { "lineHeight": "1.3", "fontWeight": "600" }],
        "display-hero-mobile": ["48px", { "lineHeight": "1.1", "fontWeight": "300" }],
        "body-lg": ["20px", { "lineHeight": "1.7", "fontWeight": "400" }],
        "technical-mono": ["13px", { "lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "400" }],
        "display-hero": ["80px", { "lineHeight": "1.1", "letterSpacing": "0", "fontWeight": "300" }],
        "body-md": ["16px", { "lineHeight": "1.625", "fontWeight": "400" }],
        "label-md": ["14px", { "lineHeight": "1.2", "fontWeight": "500" }],
        "headline-lg-mobile": ["32px", { "lineHeight": "1.2", "fontWeight": "400" }],
        "headline-lg": ["48px", { "lineHeight": "1.2", "fontWeight": "400" }]
      },
      "animation": {
        "infinite-scroll": "infinite-scroll 40s linear infinite",
      },
      "keyframes": {
        "infinite-scroll": {
          "from": { transform: "translateX(0)" },
          "to": { transform: "translateX(calc(-50%))" },
        }
      }
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
